version: "3.9"
   
services:
  db:
    image: postgis/postgis:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: 
      - prod.env
    ports:
      - "5432:5432"
    expose:
      - "5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - prod.env
    expose: 
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./files:/files
      - ./code:/code
    depends_on:
      - db
